### ISSUE TITLE
Could not fetch from <ip>/api/<username>/lights

### ISSUE THREAD

**Issue by Michdo93** [LarsBergqvist/philips_hue_react_app#9]
Hi,

I got the error that I `Could not fetch from <ip>/api/<username>/lights`.

Well if I use the API Debug tool http://<ip>/debug/clip.html, the /api/<username>/lights get request works well. There I receive in the message body the username and in the commmand response all lights.

Also I tried to ping the ip address and it works. So it is probably not an network issue.

Thanks in advace!

**Comment by Michdo93** [comment]
I also tried it with a new user. The same issue.

**Comment by LarsBergqvist** [comment]
The only time I have seen this error is when the ip-address of the hue-bridge is incorrectly specified in config.json. For my system, config.json looks like this (scrambled username):
{
  "apiUrl": "http://192.168.1.232",
  "username": "KFtjVEVVf5LupQdxQYPry8xYSXmKanZZ0-5opH5a"
}

**Comment by Michdo93** [comment]
Of course. It was my fault. I just forget `http`. It works well.

**Comment by LarsBergqvist** [comment]
No worries! It was not obvious from the README that an http:// prefix is neeed. I will clarify.
